name: Deploy Expo Web App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: web

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: web/package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Install Expo
        run: npm install expo

      - name: Build web app
        run: npx expo export --platform web

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: web/dist
